config/routes.rb
Rails.application.routes.draw do
  resources :cuestionarios
  resources :h_preguntas
  resources :preguntas
  resources :usuarios

  devise_for :users, controllers: { registrations: :registrations }

  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/main_layout/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">
      <span class="pull-right hidden-xs">
        Servicio Nacional de Aprendizaje.
      </span>
      <strong>Copyright © 2016 <a href="#">SENA</a></strong>.
      Todos los derechos reservados.
    </p>
  </div>
</footer>

app/views/layouts/main_layout/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SENA', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
            <% if can? :read, User %>
                <li><%= link_to 'Usuarios', usuarios_path %></li>
            <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in? %>
            <li><%= link_to 'Registrarse', new_user_registration_path %></li>
            <li><%= link_to 'Iniciar sesión', new_user_session_path %></li>
        <% else %>
            <% if current_user.cuestionario.blank? %>
                <li><%= link_to 'Cuestionario', cuestionarios_path %></li>
            <% elsif current_user.cuestionario.present? && !current_user.cuestionario.estado %>
                <li><%= link_to 'Cuestionario', get_cuestionario_url %></li>
            <% else %>
                <li><%= link_to 'Resultado', current_user.cuestionario %></li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.nombre %>
                <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Editar cuenta', edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Cerrar sesión', destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>