config/routes.rb
Rails.application.routes.draw do
  resources :cuestionarios
  resources :h_preguntas
  resources :preguntas
  resources :usuarios

  devise_for :users, controllers: { registrations: :registrations }

  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cuestionario.rb
class Cuestionario < ApplicationRecord
  belongs_to :user
  has_many :respuestas, dependent: :destroy

  accepts_nested_attributes_for :respuestas

  def get_respuestas(pregunta)
    if self.respuestas.any?
      self.respuestas.where(pregunta: pregunta).any? ? self.respuestas.where(pregunta: pregunta) : self.respuestas.build
    else
      self.respuestas.build
    end
  end

  def resultado_labels
    if self.user.genero
      ['Natural', 'Tradicional', 'Elegante', 'Romántico', 'Seductor', 'Creativo', 'Drámatico']
    else
      ['Natural', 'Tradicional', 'Elegante', 'Romántica', 'Seductora', 'Creativa', 'Drámatica']
    end
  end

  def resultados
    [self.get_a, self.get_b, self.get_c, self.get_d, self.get_e, self.get_f, self.get_g]
  end

  def get_a
    self.respuestas.where(opcion: 1).count
  end

  def get_b
    self.respuestas.where(opcion: 2).count
  end

  def get_c
    self.respuestas.where(opcion: 3).count
  end

  def get_d
    self.respuestas.where(opcion: 4).count
  end

  def get_e
    self.respuestas.where(opcion: 5).count
  end

  def get_f
    self.respuestas.where(opcion: 6).count
  end

  def get_g
    self.respuestas.where(opcion: 7).count
  end

  def get_step
    case self.paso
      when 1
        :pregunta_uno
      when 2
        :pregunta_dos
      when 3
        :pregunta_tres
      when 4
        :pregunta_cuatro
      when 5
        :pregunta_cinco
      when 6
        :pregunta_seis
      when 7
        :pregunta_siete
      when 8
        :pregunta_ocho
      when 9
        :pregunta_nueve
      when 10
        :pregunta_diez
      when 11
        :pregunta_once
      when 12
        :pregunta_doce
      when 13
        :pregunta_trece
      when 14
        :pregunta_catorce
      when 15
        :pregunta_quince
      when 16
        :pregunta_dieciseis
      when 17
        :pregunta_diecisiete
    end
  end
end

app/controllers/cuestionarios_controller.rb
class CuestionariosController < ApplicationController
  load_and_authorize_resource
  before_action :set_cuestionario, only: [:show, :edit, :update, :destroy]

  # GET /cuestionarios
  # GET /cuestionarios.json
  def index
    @cuestionarios = Cuestionario.all
  end

  # GET /cuestionarios/1
  # GET /cuestionarios/1.json
  def show
  end

  # GET /cuestionarios/new
  def new
    create
  end

  # GET /cuestionarios/1/edit
  def edit
  end

  # POST /cuestionarios
  # POST /cuestionarios.json
  def create
    @cuestionario = Cuestionario.new
    @cuestionario.user_id = current_user.id

    respond_to do |format|
      if @cuestionario.save
        if @cuestionario.user.try(:genero)
          url = h_pregunta_url(:pregunta_uno)
        else
          url = pregunta_url(:pregunta_uno)
        end
        format.html { redirect_to url, notice: 'Cuestionario was successfully created.' }
        format.json { render :show, status: :created, location: @cuestionario }
      else
        format.html { render :new }
        format.json { render json: @cuestionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cuestionarios/1
  # PATCH/PUT /cuestionarios/1.json
  def update
    respond_to do |format|
      if @cuestionario.update(cuestionario_params)
        format.html { redirect_to @cuestionario, notice: 'Cuestionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @cuestionario }
      else
        format.html { render :edit }
        format.json { render json: @cuestionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cuestionarios/1
  # DELETE /cuestionarios/1.json
  def destroy
    @cuestionario.destroy
    respond_to do |format|
      format.html { redirect_to cuestionarios_url, notice: 'Cuestionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cuestionario
    @cuestionario = Cuestionario.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cuestionario_params
    params.require(:cuestionario).permit(:user_id, :estado, :paso,
                                         respuestas_attributes: [:id, :pregunta, :opcion])
  end
end

app/helpers/cuestionarios_helper.rb
module CuestionariosHelper
  def get_cuestionario_url
    if current_user.genero
      h_pregunta_path(current_user.cuestionario.get_step)
    else
      pregunta_path(current_user.cuestionario.get_step)
    end
  end
end

app/views/cuestionarios/_form.html.erb
<%= simple_form_for(@cuestionario) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cuestionarios/edit.html.erb
<h1>Editing Cuestionario</h1>

<%= render 'form', cuestionario: @cuestionario %>

<%= link_to 'Show', @cuestionario %> |
<%= link_to 'Back', cuestionarios_path %>

app/views/cuestionarios/index.html.erb
<div class="jumbotron">
  <h1>Cuestionario de estilo</h1>
  <p>
    Hola <%= current_user.nombre %>, el cuestionario cuenta de <%= current_user.genero ? '14' : '17' %> preguntas
    de unica respuesta, que lo disfrutes.
  </p>
  <%= link_to 'Iniciar cuestionario', new_cuestionario_path, class: 'btn btn-primary' %>
</div>

app/views/cuestionarios/new.html.erb
<h1>New Cuestionario</h1>

<%= render 'form', cuestionario: @cuestionario %>

<%= link_to 'Back', cuestionarios_path %>

app/views/cuestionarios/show.html.erb
<div class="page-header text-center">
  <h1>Resultado</h1>
</div>

<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <canvas id="myChart"></canvas>
  </div>
  <script>
    var ctx = $("#myChart");
    var data = {
      labels: <%= raw @cuestionario.resultado_labels %>,
      datasets: [
        {
          label: "Mi Estilo",
          backgroundColor: "rgba(179,181,198,0.2)",
          borderColor: "rgba(179,181,198,1)",
          pointBackgroundColor: "rgba(179,181,198,1)",
          pointBorderColor: "#fff",
          pointHoverBackgroundColor: "#fff",
          pointHoverBorderColor: "rgba(179,181,198,1)",
          data: <%= raw @cuestionario.resultados %>
        }
      ]
    };
    var options = {
      scale: {
        reverse: false,
        ticks: {
          beginAtZero: true
        }
      }
    };
    var myRadarChart = new Chart(ctx, {
      type: 'radar',
      data: data,
      options: options
    });
  </script>
</div>