config/routes.rb
Rails.application.routes.draw do
  resources :cuestionarios
  resources :h_preguntas
  resources :preguntas
  resources :usuarios

  devise_for :users, controllers: { registrations: :registrations }

  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  load_and_authorize_resource :user, parent: false

  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = User.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = User.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = User.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_path(@usuario), notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_path(@usuario), notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_usuario
    @usuario = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def usuario_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :nombre, :tipo_identificacion, :nro_identificacion,
                                 :fecha_nacimiento, :lugar_nacimiento, :lugar_residencia,
                                 :genero, :telefono, role_ids: [])
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Editar usuario</h3>
    </div>
    <%= simple_form_for @usuario, url: usuario_path(@usuario) do |f| %>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-12">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <%= f.input :email, required: true, autofocus: true %>
            </div>
            <div class="col-md-6">
              <%= f.input :nombre %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <%= f.input :tipo_identificacion, as: :select, collection: @usuario.tipo_identificacion_collection,
                          prompt: false %>
            </div>
            <div class="col-md-6">
              <%= f.input :nro_identificacion %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <%= f.input :fecha_nacimiento, as: :date_picker %>
            </div>
            <div class="col-md-6">
              <%= f.input :lugar_nacimiento %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <%= f.input :telefono %>
            </div>
            <div class="col-md-6">
              <%= f.input :lugar_residencia %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <%= f.input :password, autocomplete: "off", hint: "Dejalo en blanco si no quieres cambiarla", required: false %>
            </div>
            <div class="col-md-6">
              <%= f.input :password_confirmation, required: false %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <%= f.input :role_ids, as: :check_boxes, collection: Role.all, value_method: :id, label_method: :nombre_capitalize, wrapper: :vertical_radio_and_checkboxes %>
            </div>
            <div class="col-md-6">
              <%= f.input :genero, as: :radio_buttons, collection: [['Masculino', true], ['Femenino', false]],
                          wrapper: :vertical_radio_and_checkboxes %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <%= link_to "Regresar", :back, class: 'btn btn-default' %>
              <%= f.button :submit, "Actualizar" %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/usuarios/edit.html.erb
<%= render 'form' %>

app/views/usuarios/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Usuarios</h3>
  </div>
  <div class="panel-body table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>Correo eletrónico</th>
        <th>Nombre</th>
        <th>Tipo de identificación</th>
        <th>Número de identificación</th>
        <th>Género</th>
        <th class="text-center">Acciones</th>
      </tr>
      </thead>
      <tbody>
      <% @usuarios.each do |usuario| %>
          <tr>
            <td><%= usuario.email %></td>
            <td><%= usuario.nombre %></td>
            <td><%= usuario.get_tipo_identificacion %></td>
            <td><%= usuario.nro_identificacion %></td>
            <td><%= usuario.get_genero %></td>
            <td class="text-center">
              <%= link_to 'Detalles', usuario_path(usuario), class: 'btn btn-sm btn-info' %>
              <%= link_to 'Editar', edit_usuario_path(usuario), class: 'btn btn-sm btn-warning' %>
              <%= link_to 'Eliminar', usuario_path(usuario), method: :delete, data: {confirm: '¿Esta seguro?'}, class: 'btn btn-sm btn-danger' %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/usuarios/show.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @usuario.nombre %></h3>
    </div>
    <table class="table">
      <tbody>
      <tr>
        <th>Correo electrónico:</th>
        <td><%= @usuario.email %></td>
      </tr>
      <tr>
        <th>Nombre:</th>
        <td><%= @usuario.nombre %></td>
      </tr>
      <tr>
        <th>Tipo de identificación:</th>
        <td><%= @usuario.get_tipo_identificacion %></td>
      </tr>
      <tr>
        <th>Número de identificación:</th>
        <td><%= @usuario.nro_identificacion %></td>
      </tr>
      <tr>
        <th>Fecha de nacimiento</th>
        <td><%= @usuario.fecha_nacimiento %></td>
      </tr>
      <tr>
        <th>Lugar de nacimiento:</th>
        <td><%= @usuario.lugar_nacimiento %></td>
      </tr>
      <tr>
        <th>Género:</th>
        <td><%= @usuario.get_genero %></td>
      </tr>
      <tr>
        <th>Lugar de residencia:</th>
        <td><%= @usuario.get_lugar_residencia %></td>
      </tr>
      <tr>
        <th>Número de contacto:</th>
        <td><%= @usuario.get_telefono %></td>
      </tr>
      <tr>
        <th>Autorización:</th>
        <td><%=@usuario.roles.map(&:nombre_capitalize).join(', ') %></td>
      </tr>
      </tbody>
    </table>
    <div class="panel-footer"><%= link_to 'Regresar', usuarios_path, class: 'btn btn-sm btn-default' %></div>
  </div>
</div>